### ISSUE TITLE
Use with browserify

### ISSUE THREAD

**Issue by Yoyogi** [roadmanfong/react-cropper#1]
Hello there,

Is there a way to use this component with Browserify ? I use reactify to compile all my jsx files into one js file, but on compilation, I get an error because of the require('cropper/dist/cropper.css'); line.
The exact error is: 
.cropper-container {
^
ParseError: Unexpected token

Thanks for your help

**Comment by alxs24** [comment]
i solved it by deleting the line 7 of the file: react-cropper/dist/react-cropper.js.
then get the css from react-cropper/node_modules/cropper/dist/cropper.css and put link it from my proyect html

**Comment by roadmanfong** [comment]
Sorry for the late reply.
I think you can try https://github.com/cheton/browserify-css
and compile it with command line 

```shell
 browserify -t reactify -g browserify-css index.jsx > bundle.js
```

**Comment by Toynbert** [comment]
To include browserify-css via gulp globally, mine looks like this:
```
var b = browserify({
		entries: [path.ENTRY_POINT],
		debug: true,
		cache: {}, packageCache: {}, fullPaths: true
	});

	b.transform(babelify);
	b.transform(browserifycss, {global: true});
```

**Comment by roadmanfong** [comment]
Thanks. I'll put this into README.md

**Comment by ravic1995** [comment]
I am using webpack and still getting this error 
I am using the correct loaders 
Any help
