### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by nbwar** [roadmanfong/react-cropper#10]
After install react-cropper just starting my dev server gives me

```
/node_modules/react-cropper/node_modules/cropper/dist/cropper.js:27
  var $window = $(window);

ReferenceError: window is not defined
```

**Comment by nbwar** [comment]
This is an issue with cropper and not react-cropper.

A quick workaround is
```
let isClient = typeof window !== "undefined";
let Cropper = isClient ? require('react-cropper') : function() {};
```

**Comment by roadmanfong** [comment]
Did you run this code on server?
To my knowledge, `window` is a global object provided by browser. It should
always be accessible if it runs in client browser.

2015-09-18 8:23 GMT+08:00 Nicholas Wargnier <notifications@github.com>:

**Comment by nbwar** [comment]
It gets loaded into a Node environment since I'm using Server Side Rendering. The problem is that the `Cropper` library doesn't guard against the `window` object being `undefined`. I've opened an issue with them see https://github.com/fengyuanchen/cropper/issues/453

**Comment by OKNoah** [comment]
cropper.js is not likely to fix this as there is really no use case for it in vanilla JS or jQuery, that I can think of. Would be great to have this work out of the box. Can this be re-opened?

**Comment by samstr** [comment]
Would like this to work out of the box
