### ISSUE TITLE
为什么宽度自适应了, 高度却没有自适应, 是有什么参数可以控制的吗

### ISSUE THREAD

**Issue by jackYouth** [roadmanfong/react-cropper#120]
代码:
<Cropper
ref="cutImg"
src={this.url}
style={{height: '100%', width: '100%'}}
// Cropper.js options
aspectRatio={1}
guides={false}
checkCrossOrigin={false}
autoCropArea={1}
minCropBoxWidth={30}
minCropBoxHeight={30}
zoomOnWheel={false}
movable={false}
maxWidth={400}
maxHeight={400}
crop={(e) => {
let { x, y, width, height } = e.detail;
let cutimg = this.refs.cutImg;
this.postData = {
module: this.num,
url: this.url,
x: Math.floor(x),
y: Math.floor(y),
w: Math.floor(width),
h: Math.floor(height)
} || {};
this.setState({
cropperW: Math.floor(cutimg.getCropBoxData().width)
});
}}
/>
效果:
![image](https://user-images.githubusercontent.com/23489336/63002262-15246280-bea8-11e9-8080-af6650adb4bf.png)

**Comment by roadmanfong** [comment]
請參考 https://fengyuanchen.github.io/cropperjs/，這個只是包成 react 型式的 package
