### ISSUE TITLE
Cropper not loading

### ISSUE THREAD

**Issue by outspokeio** [roadmanfong/react-cropper#137]
The cropper has been working great and thus far has been quite reliable. Tonight I went into our dev environment and images are not loading. I tracked from file select through our Sharp correction endpoint back through return and everything looks fine - I've got the src input in state as a data:image/jpeg;base64 (followed by binary stream returned from server)... and it's been smooth up until tonight.

Has something changed externally that might explain this behavior? At this point I'm stuck and not sure how to proceed. Thank you.

**Comment by kylanhurt** [comment]
How did you fix it?

**Comment by outspokeio** [comment]
To be frank I don't recall - but if it helps here's the snippet that I use to process the initial server return:

let newImage = Buffer.from(correctedImage, 'binary').toString('base64');
this.setState({ src: 'data:image/jpeg;base64,'+newImage });

<ReactCrop
  src={src}
  ...
