### ISSUE TITLE
Low Framerate

### ISSUE THREAD

**Issue by pezza3434** [roadmanfong/react-cropper#14]
Hi,

First of all, congratulations on porting it over, it looks good!

The only thing I've noticed at the moment is that the framerate seems significantly lower than the original plugin. Is there a reason for this?

**Comment by dilizarov** [comment]
@pezza3434 I'm experiencing this too. From my own testing, the frame rate seems to be lower because of the crop callback.

For example:

    crop: function () {
      this.setState({ preview: this.refs.cropper.getCroppedCanvas().toDataURL()})
    }

somewhere in render:

    <Cropper aspectRatio={1 / 1}
              guides={false}
              src={this.state.cropper_source}
              ref='cropper'
              crop={this.crop} />

When I take out the crop callback, everything works much more smoothly. The moment I put it back in, the frame-rate drops.

**Comment by roadmanfong** [comment]
@dilizarov you are right. In the previous demo, I use  `this.refs.cropper.getCroppedCanvas().toDataURL()` to render the preview. which costs a lot of performance. If you want to show preview. please take a look of [preview](https://github.com/fengyuanchen/cropper#preview).  To use it in react-cropper please refer to https://github.com/roadmanfong/react-cropper/blob/master/example/index.js#L54
