### ISSUE TITLE
after changing an option the component doesn't re-render properly

### ISSUE THREAD

**Issue by riccardolorenzon** [roadmanfong/react-cropper#16]
Hi,

if you pass the option ```data``` to the component from a parent component the former doesn't re render properly. 
If you pass another option, for example ```src```, the re render works.

**Comment by roadmanfong** [comment]
Sorry for the late reply. `src` and `aspectRatio` might be the only two props can trigger re-render. I suggest you use something like `this.refs.cropper.setData` for now. I'm considering refactor this. 

Thanks for your feedback.

**Comment by roadmanfong** [comment]
From version `0.7.0` you can pass more options such as `data`. However, there're options can't be altered after component mount. Please see README to know more.

**Comment by designbyadrian** [comment]
> From version `0.7.0` you can pass more options such as `data`. However, there're options can't be altered after component mount. Please see README to know more.

There is no mention of this in the read me.
