### ISSUE TITLE
Upgrade to Cropper 2

### ISSUE THREAD

**Issue by levivoelz** [roadmanfong/react-cropper#19]
Hi, do you have any plans to upgrade this component to use the latest Cropper library? If so, when do you think you will release it? If not, any tips on doing it myself and submitting a pull request?

**Comment by roadmanfong** [comment]
Sorry, I have been busy recently. I'll try to upgrade to the latest Cropper
in the coming week.
2016年1月5日 13:18於 "Levi Voelz" <notifications@github.com>寫道：

**Comment by levivoelz** [comment]
Ok, thanks!

**Comment by roadmanfong** [comment]
Hi I just updated  react-cropper to 0.6.0 with https://github.com/fengyuanchen/cropperjs. This update remove the dependency of jQuery. If you have any problem please let me now.
