### ISSUE TITLE
Rotate

### ISSUE THREAD

**Issue by foodaka** [roadmanfong/react-cropper#20]
Thanks for the awesome plugin. Are there options to rotate the image?

Cheers

**Comment by roadmanfong** [comment]
Yes you can.
This is a react component based on cropperjs
Please refer to https://github.com/fengyuanchen/cropperjs#rotatedegree

it would be something like 
```js
onClick(e) {
  this.refs.yourcropperref.rotate(30)
},
//...
render() {
  return <Cropper ref='yourcropperref' />
}

```

**Comment by foodaka** [comment]
cool thanks fong
