### ISSUE TITLE
Crop zone exceeds natural image size

### ISSUE THREAD

**Issue by ClaudiuHar** [roadmanfong/react-cropper#24]
The image returned by cropper is much larger than the original image.

It seems that fengyuanchen cropper had this issue, but it is fixed now. See issue:
https://github.com/fengyuanchen/cropper/issues/34

Can you confirm witch version of fengyuanchen is used by react-cropper? 

Also I still have this problem, so when uploading a 300kb file it become 1.9Mb after cropping; the difference is huge.

**Comment by roadmanfong** [comment]
Could you check what version of react-cropper are you using?

The latest version of recat-cropper is using https://www.npmjs.com/package/cropperjs not https://www.npmjs.com/package/cropper.

If you use the latest version of react-cropper 0.6.2 and still have this problem, would you please attach the screenshot to this discussion?

**Comment by ClaudiuHar** [comment]
React code where I call react-cropper: 

`var ReactAddAndCropImages = React.createClass({
    ...
    _cropImage: function(){
        var newImage = {
            ...
            data: this.refs.cropper.getCroppedCanvas().toDataURL(),
        };
        ...
    },
   ...
    render: function(){
        return(
                                <ReactCropper
                                    ref='cropper'
                                    src={this.state._originalImage}
                                    style={{height: 400, width: 600}}
                                    autoCropArea={0.2}
                                    background={false}
                                    dragMode='move'
                                    viewMode='0'
                                    cropBoxResizable={false}
                                    cropBoxMovable={false}
                                    strict={false}
                       
                                    minCropBoxWidth={600}
                                    minCropBoxHeight={400}
                                    guides={false}

                                    minCanvasWidth={600}
                                    minCanvasHeight={400}

                                    crop={this._crop} />
                       ...`

1 I add a jpeg image but cropper returns a png;
2 data returned by cropper at: data: this.refs.cropper.getCroppedCanvas().toDataURL(), is actually in different size that the original one.

Screen shot:
![screen shot 2016-03-15 at 4 17 57 pm](https://cloud.githubusercontent.com/assets/17842686/13768394/b7f8a072-eac9-11e5-9c99-36e28a42f610.png)
![screen shot 2016-03-15 at 4 18 25 pm](https://cloud.githubusercontent.com/assets/17842686/13768395/b7f8f8f6-eac9-11e5-8702-bf2c7477f76d.png)
![screen shot 2016-03-15 at 4 18 38 pm](https://cloud.githubusercontent.com/assets/17842686/13768396/b7f92a9c-eac9-11e5-8f05-f5831b32f17b.png)
![screen shot 2016-03-15 at 4 18 47 pm](https://cloud.githubusercontent.com/assets/17842686/13768397/b7f91570-eac9-11e5-9c64-0e27e97ab6b1.png)

Uploaded images:
![9658_1_other_wallpapers](https://cloud.githubusercontent.com/assets/17842686/13768434/2b42e132-eaca-11e5-8356-87b8ce56a183.jpg)
![475364505a57a744d4a8a0c1df301503a42bce738b52c369346647107ff44990wallpaper_hd_assassins_creed_3_games_wide](https://cloud.githubusercontent.com/assets/17842686/13768439/3ca91d9c-eaca-11e5-88a9-da330591d065.jpg)


result images
![frp_image_56e79b745ad79](https://cloud.githubusercontent.com/assets/17842686/13768424/0d8c8666-eaca-11e5-92b7-bf15d1fd2ada.png)

![frp_image_56e79b745238f](https://cloud.githubusercontent.com/assets/17842686/13768405/d74a98f4-eac9-11e5-8289-4f88d9404d08.png)

**Comment by ClaudiuHar** [comment]
Any suggestions?

**Comment by ClaudiuHar** [comment]
It turns out that the issue is the image, not the cropper. 
Thank you.

**Comment by PGDJ** [comment]
@ClaudiuHar may I ask how you handled the uploading of multiple images and getting rid of the background sizing?

**Comment by oliviazhangjuan** [comment]
Is the problem solved?@ClaudiuHar

**Comment by bowlingQ** [comment]
It seems that the problem is still there, and it is related to the picture, sometimes it is 10 times larger, sometimes only 2 times larger
