### ISSUE TITLE
React.createElement: type should not be null, undefined, boolean, or number. 

### ISSUE THREAD

**Issue by simax** [roadmanfong/react-cropper#25]
When I upgraded to the 0.6.2 version of react-cropper. I kept getting the following error when React was trying to render it to the page.

`warning.js:45Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).`

So I create a brand new project and used your example from the readme

```
var Cropper = require('react-cropper');
var Demo = React.createClass({
  _crop: function(){
    // image in dataUrl
    console.log(this.refs.cropper.getCroppedCanvas().toDataURL());
  },

  render: function() {
    return (
      <Cropper
        ref='cropper'
        src='http://fengyuanchen.github.io/cropper/img/picture.jpg'
        style={{height: 400, width: '100%'}}
        // Cropper.js options
        aspectRatio={16 / 9}
        guides={false}
        crop={this._crop} />
    );
  }
});
```

I still experienced the same issue. Changing the line 
`var Cropper = require('react-cropper');` to `var Cropper = require('react-cropper').default`; 
cleared the problem. 

It may be worth adding a note to the readme in case others experience the same problem.

Thanks for your work on react-cropper.

**Comment by roadmanfong** [comment]
Could you tell me how do you build your code? Webpack or browserify? And what version did you use? If you can put your project on Github that will be very helpful.

**Comment by simax** [comment]
Github project https://github.com/simax/react-cropper-demo/tree/master

**Comment by roadmanfong** [comment]
I think I know what's going on. It's because babeljs change the way export module. http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

**Comment by roadmanfong** [comment]
`import Cropper from 'react-cropper'`
https://github.com/roadmanfong/react-cropper-demo/blob/master/main.js
This works too.

I added require function usage in `README.md`, Thank you for your feedback.

**Comment by OKNoah** [comment]
@roadmanfong Unfortunately this module will not work with `import` in my case, since there is server-side rendering and I have to do.

`const Cropper = __CLIENT__ ? require('react-cropper') : null;`

Then it took me some time to learn I had to put `.default` as well. This is why I think your component should take care of the server-side rendering issue.
