### ISSUE TITLE
Require css crashes Meteor

### ISSUE THREAD

**Issue by dufia** [roadmanfong/react-cropper#26]
Latest Meteor lets you use npm but

    require('cropperjs/dist/cropper.css')

in react-cropper.js crashes it. I can comment it out and its working fine.

Is it intended? I didn't know you can require css with nodejs.

**Comment by roadmanfong** [comment]
Yes. node.js can't require css file. 
But if you use webpack or browserify to build your app. There are css loader plugins to handle this special kind of require.
Please see my readme file to know how use in webpack and browserify.

I never use Meteor before. I think maybe there's some css require plugin in Meteor too.

**Comment by roadmanfong** [comment]
From version 0.7.0, you need to include css file on your own. It won't break your Meteor now.

**Comment by dufia** [comment]
I want to thank you for fixing it brother
