### ISSUE TITLE
added typescript definitions for this lib

### ISSUE THREAD

**Issue by stepancar** [roadmanfong/react-cropper#28]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/react-cropper

**Comment by roadmanfong** [comment]
Hi. Is there anything need to be done for this issue? or you just inform me about this?

**Comment by stepancar** [comment]
Hello, @roadmanfong. If you will add any additional functionality, please notify me. You can write in Readme that this module have defitions for typescript. Thank you!

**Comment by rasdaniil** [comment]
@stepancar 
Hi Stepan
There is an error typescript 2.4 throws out, line 20 should have `void` as a second generic type for `React.Component`, otherwise it doesn't compile
Spasibo

**Comment by TheLogan** [comment]
Was type definition removed? I can't seem to find it and the link returns a 404

**Comment by stepancar** [comment]
@TheLogan 
https://www.npmjs.com/package/@types/react-cropper
But i think, it obsolete. Try to use, and if it's not working - mention me in PR

**Comment by TheLogan** [comment]
I'm afraid I can't make it work at all.
