### ISSUE TITLE
Cannot find cropper.css in dist

### ISSUE THREAD

**Issue by Heboy** [roadmanfong/react-cropper#29]

**Comment by roadmanfong** [comment]
https://github.com/roadmanfong/react-cropper#installation

**Comment by Heboy** [comment]
Of course I read it ,but there`s no cropper.css in node_modules/react-cropper/cropperjs/dist/cropper.css,I use npm to install it

**Comment by roadmanfong** [comment]
That is weired. I just installed it, and saw it. What is inside the folder?
2016年4月10日 13:15於 "Heboy" <notifications@github.com>寫道：

**Comment by Heboy** [comment]
only react-cropper.js in dist
I install it again but no works

**Comment by roadmanfong** [comment]
it's not in `node_modules/ract-cropper/dist`, it's in `node_modules/react-cropper/node_modules/cropperjs/dist/cropper.css`

**Comment by Heboy** [comment]
well,here`s my dictionary
![image](https://cloud.githubusercontent.com/assets/5352769/14417132/2a03d5d6-ffe4-11e5-9f7c-a5aa3e417d5d.png)

**Comment by roadmanfong** [comment]
Maybe your file explore hide `node_modules` folder. 

Did you try to find this file through CLI?
`cd node_modules/react-cropper/node_modules/cropperjs/dist/`

![image](https://cloud.githubusercontent.com/assets/2047789/14418221/65bc67d6-ffef-11e5-83e5-255cd777dd31.png)

**Comment by Heboy** [comment]
I tried it but no node_modules folder and I copy the bundle.css in your demo and hope it works

**Comment by roadmanfong** [comment]
I will be surprised if it works. This project have dependency on [cropper.js](https://www.npmjs.com/package/cropperjs) so `node_modules/ract-cropper/node_modules` must exist. If it doesn't not only the CSS issue, the whole react component won't work. 

In other words, when you `npm install react-cropper`, all dependency package will be automatically installed inside `node_modules/react-cropper/node_modules` folder.

You can see the dependency of this package [here](https://github.com/roadmanfong/react-cropper/blob/master/package.json#L32).

Maybe you can try to start a new clean project to see if the file `node_modules/react-cropper/node_modules/cropperjs/dist/cropper.css` exists and make sure there are no any error or warning message during installation?

**Comment by maximeloizeau** [comment]
Apparently, from release 3.0.0 of npm, the dependencies are installed at the root of node_modules instead of inside each module.
See : https://github.com/npm/npm/releases/tag/v3.0.0 (Flat, flat, flat! paragraph)

I also didn't find the css in the specified folder, it was simply in `node_modules/cropperjs/dist/cropper.css`

**Comment by roadmanfong** [comment]
Thanks for clarifying this.

**Comment by OKNoah** [comment]
Documentation still seems to be out of date.

**Comment by DraconView** [comment]
por si acaso alguien mas le sucede me faltaba el archivo css lo busque de otro proyecto y tambien como uso pnpm renombran las carpetas solucione con eso

**Comment by DraconView** [comment]
Just in case someone else happens, I was missing the css file, I looked for it from another project and also how I use pnpm to rename the folders, I solved it with that

**Comment by OmkoBass** [comment]
For anyone having this problem, [check this link out](https://fengyuanchen.github.io/cropperjs/guide.html#introduction). 

It says that in the new version "CSS-in-JS" is included. So you can just include the `cropper.js` file and try it out then.
If it still doesn't work then just install the latest version 1 of cropper and then you will have the `cropper.css` file in the `dist` directory.

**Comment by HarukiFT** [comment]
@OmkoBass bro, thx you!
