### ISSUE TITLE
Let cropper height vary by image height

### ISSUE THREAD

**Issue by dantman** [roadmanfong/react-cropper#3]
In my original non-react code. I let my cropper height vary by the height of the image instead of fixing it at one size.

However the `display: none;` stops cropper from inheriting the height of the image and it simply shrinks to the minimum size.

I don't want to just drop the `display: none;` from react-cropper and change things for everyone else. But I would like to find a way to make react-cropper or cropper explicitly opt-in to this behaviour.

**Comment by roadmanfong** [comment]
The reason I add `display:none;` is that it will show large image and then hide it after cropper init done.

Do you think `opacity: 0` is a good idea?

**Comment by dantman** [comment]
That could work. Though that would change the size of the cropper for other people.

**Comment by roadmanfong** [comment]
Done!
