### ISSUE TITLE
Canvas to Blob -> toBlob is not a function

### ISSUE THREAD

**Issue by JasaNiklanovic** [roadmanfong/react-cropper#31]
Hey guys, this plugin is amazing though i am having problems with getting the base64 output to my server via ajax call. If i just try to send the getCroppedCanvas.toDataUrl() my browser almost crashes due to the huge base64 string so i am looking at the toBlob method from the jquery cropper.

I was trying to approach it like this:
this.refs.cropper.getCroppedCanvas().toBlob() ...
I get toBlob is not a function; from researching this happens because the whole canvas is not rendered yet so i would have to wrap it inside a "built" function which i don't know how to do in this example.

Can anybody help me with a working example on how to post the cropped image via ajax? Any form is fine.

Regards, Jasa

**Comment by roadmanfong** [comment]
I tried `this.refs.cropper.getCroppedCanvas().toBlob()`, and it works.
![react-cropper_example](https://cloud.githubusercontent.com/assets/2047789/14612344/2808bfea-05c9-11e6-9d69-e11ce1916e87.png)

Did you set `ref` correctly? if possible please paste your react component here might be helpful.

This react project is based on `cropperjs`, they have good example of uploading image. https://github.com/fengyuanchen/cropperjs#getcroppedcanvasoptions

**Comment by JasaNiklanovic** [comment]
Thanks for your response; i figured out that "toBlob" is actually only available on Chrome 50+ and my version vas 49; so after i updated my browser it worked normally. Though i have decided just to work with the dataUrl base64 since the blob function is so unsupported.
