### ISSUE TITLE
Unused property warning in React 15.2.0

### ISSUE THREAD

**Issue by HadrienPierart** [roadmanfong/react-cropper#33]
With React 15.2.0, any unrecognized props assigned to DOM elements will throw a warning. In the case of this library, the following warning occurs:

```
Warning: 
Unknown props `aspectRatio`, `guides`, `zoomable`, `crop`, `build`, `built`, `dragMode`, `scaleX`, `scaleY`, `enable`, `zoomTo`, `rotateTo` on <div> tag. 
Remove these props from the element.
For details, see https://fb.me/react-unknown-prop
    in div (created by ReactCropper)
```

**Comment by HadrienPierart** [comment]
You can check over here for an interesting discussion on how to fix this warning :
https://github.com/Hacker0x01/react-datepicker/issues/517

**Comment by HadrienPierart** [comment]
Do you want me to propose a PR following what was chosen in the discussion if you dont have the time to implement this yourself ?

**Comment by dingdada** [comment]
I have the same problem, I hope you can fix it.

**Comment by gentgaashi** [comment]
Yep same here, just wanted to ask if there is any chance of fixing this in the near future.

**Comment by roadmanfong** [comment]
Kind of busy recently.
Any pull request is welcome.

**Comment by alexdong** [comment]
@roadmanfong Just submitted a PR for this. Would love to hear your comments on the package.json changes.

**Comment by roadmanfong** [comment]
@alexdong, thank you for your contribution. 
I also update eslint to `3.3.1`, and modified some code let the code to meet the rule of new `eslint-airbnb-config`.
I Just publish `0.9.1` Please let me know if it works well.
