### ISSUE TITLE
crossOrigin 图片跨域的问题怎么解决

### ISSUE THREAD

**Issue by baijingmsn** [roadmanfong/react-cropper#47]
图片传成功以后遇到跨域的问题

**Comment by roadmanfong** [comment]
This issues is caused by CORS.
Did you try something like http://stackoverflow.com/questions/32558374/allow-access-control-allow-origin-in-pure-javascript

**Comment by alexandrasmith00** [comment]
Also having a crossOrigin issue - the image loads fine when not in react-cropper, so I'm not sure what's happening.  What exactly should the crossOrigin parameter be set to?
