### ISSUE TITLE
Cannot find SourceMap 'cropper.js.map'

### ISSUE THREAD

**Issue by robertli0719** [roadmanfong/react-cropper#55]
When I am using wabpack with typescript, there is a warning:

WARNING in ./~/react-cropper/~/cropperjs/dist/cropper.js
Cannot find SourceMap 'cropper.js.map': Error: Cannot resolve 'file' or 'directory' ./cropper.js.map in C:\Users\liliu\Desktop\Demo\webapp\node_modules\react-cropper\node_modules\cropperjs\dist

**Comment by roadmanfong** [comment]
The source map file of cropperjs is unnecessary.  There's no `sourceMappingURL` in `node_modules\cropperjs\dist\cropper.min.js`

**Comment by rasdaniil** [comment]
@roadmanfong 
Maybe you could recompile it with sourcemaps, please? That's very annoying to see this error in webpack on every rebuild..
Thanks for the work anyways
