### ISSUE TITLE
Please remove "react" etc as npm dependencies

### ISSUE THREAD

**Issue by jmale** [roadmanfong/react-cropper#56]
Can you please remove "react" and "react-dom" from the "dependencies" section of package.json?

(but leave them in peerDependencies and devDependencies)

Our app breaks due to there being two versions of react.
Thanks!

**Comment by roadmanfong** [comment]
done
https://github.com/roadmanfong/react-cropper/commit/a3bb22e924707547ee9914b484fcde35a4ad58c3
