### ISSUE TITLE
Is there a way to fill the color of the background when cropping.

### ISSUE THREAD

**Issue by firaskrichi** [roadmanfong/react-cropper#57]
<img width="411" alt="screen shot 2017-01-11 at 3 45 36 pm" src="https://cloud.githubusercontent.com/assets/9126737/21871140/0d600cd8-d815-11e6-9897-7bc7ac95cb94.png">

Can the cropped image have a white background for example?

**Comment by roadmanfong** [comment]
please overwrite css class `.cropper-bg`

**Comment by ducmaxime** [comment]
After crop finished, the background of my image (.cropper-bg in preview) is black.

How can I configure that ?

thx
