### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by zeal29gdd** [roadmanfong/react-cropper#58]
Backend: AdonisJs
Proxy: Express-http-proxy
Frontend: React-redux

Scenario:
Right after I successfully uploaded the image, and trying to load the src to the cropper.

Error:

Access to Image at 'http://localhost:3333/images/profiles/ID1_20170206-145755.jpg?timestamp=1486364893261' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

**Comment by roadmanfong** [comment]
This issues is caused by CORS.
Did you try something like http://stackoverflow.com/questions/32558374/allow-access-control-allow-origin-in-pure-javascript

**Comment by sharkwarn** [comment]
checkCrossOrigin={false}

**Comment by chase-si** [comment]
> checkCrossOrigin={false}

it works...
actually the `react-cropper` require the `cropper.js`, just set `CrossOrigin` will be coved in cropper.js

**Comment by minsoo-web** [comment]
> checkCrossOrigin={false}

Thanks, it works fine.
but with this option you must delete `crossOrigin="anonymous"` option. Then will be fine
