### ISSUE TITLE
How to pass an initial cropArea?

### ISSUE THREAD

**Issue by ValentinH** [roadmanfong/react-cropper#60]
I would like to know if it is possible to set the initial crop area? If yes, how can I do that?

**Comment by mctenshi** [comment]
I found the way from source code. Use `data` attribute.

```
<Cropper data={{
 scaleX: -1,
}} />
```

**Comment by ValentinH** [comment]
Thanks for this. I can't try it now because I switched to another crop library...

**Comment by ValentinH** [comment]
It might be nice to add it to the documentation though.
