### ISSUE TITLE
Can't zoom the image on mobile device.

### ISSUE THREAD

**Issue by shikelong** [roadmanfong/react-cropper#64]
In my mobile chrome. if I try to zoom the image itself, (not the crop box). The picture will be lost。

But cropperjs's demo is ok.

### after zoom image use fingers:
![2017-03-23_162023](https://cloud.githubusercontent.com/assets/4499997/24238263/aa2e60da-0fe4-11e7-8006-7ba2a7a52f43.png)

Regards.

**Comment by danazkari** [comment]
IDK if it's the same issue but I'm trying to zoom on mobile and I'm getting the next warning on the demo:
![image](https://cloud.githubusercontent.com/assets/349542/24528326/2442d6fc-1563-11e7-9090-3f7aeeaa0a1a.png)
And it seems like the addEventListener implementation changed a bit https://developers.google.com/web/updates/2017/01/scrolling-intervention

FYI: I'm testing on a OnePlus 3T, Chrome 56, Android 7.0.

**Comment by matthew-dev** [comment]
+1 
I get exactly the same issue trying to zoom image on touchable laptop screen with Google Chrome v.56 and Opera v.43... in Firefox v.52 zooming works correctly

**Comment by SagiMedina** [comment]
Any solution available?

**Comment by Autushka** [comment]
Same problem here - zooming crashes the copper in Chrome on Android. Apparently, there was a similar problem with cropperjs that was fixed with the 3.x version. 
[https://github.com/fengyuanchen/cropper/issues/827](url)

**Comment by Rauttis** [comment]
Ran into the same issue, trying to zoom on mobile shifts the image in a weird way breaking the cropper.

**Comment by belief-cyf** [comment]
@shikelong   你最后找到解决方案了嘛？    我也是碰到这个问题  在平板上的chrome浏览器内方法图片会崩溃 。

**Comment by belief-cyf** [comment]
经过测试 chrome浏览器V56及以上的版本都会出现此问题

**Comment by shikelong** [comment]
@belief-cyf   Finally I disable zoom feature in mobile. I can't find a solution in the case.

**Comment by belief-cyf** [comment]
I need this zoom function    i cant disable~~

**Comment by matthew-dev** [comment]
I needed it aprox. 4 month ago, so as no provided solution I simply added buttons to provide zoom in and zoom out functions (and also disabled zoom on touch function)... It looks like this...

![cropper image](https://ibin.co/3VFjDrUfjtp8.png)

**Comment by belief-cyf** [comment]
https://github.com/fengyuanchen/cropperjs/issues/161

cropperjs V1.0.0-RC  resolve this err

Hope the author can go under the updated version

**Comment by belief-cyf** [comment]
@matthew-dev @shikelong 
I made some changes
update the  cropper
You can use this temporarily, waiting for author update this project
https://github.com/belief-cyf/react-cropper

**Comment by shikelong** [comment]
Thank you!
