### ISSUE TITLE
Remove jquery dependency

### ISSUE THREAD

**Issue by geekyme** [roadmanfong/react-cropper#7]
reactjs should provide all the events and you can easily point to elements with refs. 

We shouldn't need to add jquery to bloat up the library

**Comment by roadmanfong** [comment]
I agree with you, but this library is just a wrapper of project https://github.com/fengyuanchen/cropper, which depends on jQuery.

**Comment by roadmanfong** [comment]
https://github.com/fengyuanchen/cropper/issues/291

**Comment by bkniffler** [comment]
https://github.com/fengyuanchen/cropperjs

Its a jquery-less version.

**Comment by nhagen** [comment]
Bump---this would be a great addition (or subtraction). Requiring jquery could be a dealbreaker for us.

**Comment by geekyme** [comment]
...? @nhagen did you read the thread before bump?

**Comment by nhagen** [comment]
I don't see a resolution to this issue. Will this never be updated to use cropperjs? What am I missing?

**Comment by geekyme** [comment]
You can use https://github.com/fengyuanchen/cropperjs in componentDidMount, then everything will work.

**Comment by pbojinov** [comment]
@geekyme @nhagen I ended up forking this and adding support for the `cropperjs` project that doesn't use jQuery.

https://github.com/TAPP-TV/react-cropperjs
