### ISSUE TITLE
Version 1.0.1 not public

### ISSUE THREAD

**Issue by silvestrijonathan** [roadmanfong/react-cropper#89]
Hello!

I was trying to install version 1.0.1 which seems to handle the peer dependency warnings for React 16^, but I'm getting failures for finding the package. Was it intentional that this hasn't been made public yet?

**Comment by Zephir77167** [comment]
I think the author has forgotten to publish to NPM

**Comment by silvestrijonathan** [comment]
@Zephir77167 okay, thanks.

**Comment by Zephir77167** [comment]
@roadmanfong Hi, could you please publish 1.0.1 to NPM? Thanks in advance!

**Comment by yonajune** [comment]
I tweeted him and he just published it. :)

**Comment by roadmanfong** [comment]
done

**Comment by silvestrijonathan** [comment]
thanks!
